version: "3.8"
services:
    dots-wallet:
        build:
            context: .
            dockerfile: dots-wallet-Dockerfile
        ports:
          - "5000:5000"
        environment:
          MONGO_HOST: mongodb
    mongodb:
        image: mongo
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: secret
